name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      # Build production version
      - name: Build Production
        run: |
          cd web
          npm install
          npm run build
          cd ..
          
      # Create production zip
      - name: Create Production ZIP
        run: |
          mkdir prod
          cp -r fxmanifest.lua client shared web/build prod/
          cd prod
          zip -r ../b2-sleekprogress-prod.zip *
          cd ..
          
      # Create development zip
      - name: Create Development ZIP
        run: |
          zip -r b2-sleekprogress-dev.zip * \
          -x "prod/*" \
          -x "*.zip" \
          -x "node_modules/*" \
          -x "web/node_modules/*" \
          -x "web/build/*"
          
      # Create Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            b2-sleekprogress-prod.zip
            b2-sleekprogress-dev.zip
          draft: false
          prerelease: false
          body: |
            ## B2 Sleek Progress ${{ github.ref_name }}
            
            ### Production Build
            - Plug and play version
            - Pre-built UI
            - Ready for production use
            
            ### Development Build
            - Complete source code
            - Requires npm install and build
            - Includes all development files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}